apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-frontend
  labels:
    app: music-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: music-frontend
  template:
    metadata:
      labels:
        app: music-frontend
    spec:
      containers:
        - name: music-frontend
          image: <your-ecr-repo>/amazon-frontend:latest  # ğŸ” Replace this
          ports:
            - containerPort: 80
